In [1]:
# checking the time consume both 

In [2]:
%timeit [i**4 for i in range(1,10)]

1.37 µs ± 97.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np

In [4]:
%timeit np.arange(1,10)**4

4.05 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
# Creating Array

In [6]:
import numpy as np # if we import numpy alredy then we dont need import again
x = [1,2,3,4,5]

y = np.array(x)
print(y)
type(y)
y.ndim

[1 2 3 4 5]


1

In [7]:
def give_array(numbers):
    n = np.array(numbers)
    return n
m = [1,2,3,4,56,78,9]
x = give_array(m)
print(x)

[ 1  2  3  4 56 78  9]


In [8]:
# Creating Two Dimension Array

In [9]:
ar2 = np.array([[1,2,3,4],[4,5,6,7],[10,58,6,1]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 58  6  1]]
2


In [10]:
ar2 = np.array([(1,2,3,4),(4,5,6,7),(10,58,6,1)])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 58  6  1]]
2


In [11]:
# Creating Three Dimension Array

In [12]:
ar3 = np.array([[[1,2,3],[1,4,7],[1,5,9],[7,5,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 4 7]
  [1 5 9]
  [7 5 3]]]
3


In [13]:
# Creating nth Dimension array, 
# this function is not allowed greater than 32 Dimensions
# After that we use NPY_MAXDIMS

In [14]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [15]:
# zeros

In [16]:
ar_zero = np.zeros(5)
ar_zero

array([0., 0., 0., 0., 0.])

In [17]:
ar_tZeros = np.zeros((3,4))
ar_tZeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# Ones

In [19]:
ar_fOnens = np.ones((4,1,1,1))
ar_fOnens

array([[[[1.]]],


       [[[1.]]],


       [[[1.]]],


       [[[1.]]]])

In [20]:
# Empty

In [21]:
ar = np.array(4)
print(ar)
print(type(ar))

4
<class 'numpy.ndarray'>


In [22]:
empty_array = np.array([])
print(type(empty_array))

<class 'numpy.ndarray'>


In [23]:
# Range

In [24]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Digonal

In [26]:
ar_dig = np.eye(3)
ar_dig

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# Linspace

In [28]:
ay =np.linspace(1,10,10)
ay

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
# Rand() Functom

In [30]:
a = np.random.rand(5,1,2)
a

array([[[0.99451719, 0.07619114]],

       [[0.22070101, 0.57816616]],

       [[0.30654836, 0.1676371 ]],

       [[0.61970686, 0.33237589]],

       [[0.85174288, 0.32444056]]])

In [31]:
# randn() Function

In [32]:
b = np.random.randn(2,4,1)
b

array([[[ 0.1630503 ],
        [-0.64524939],
        [ 0.03202913],
        [ 1.25249021]],

       [[ 0.17370203],
        [-1.44074319],
        [-1.52441322],
        [ 1.65325289]]])

In [33]:
# ranf()

In [34]:
c = np.random.ranf(10)
c

array([0.0320407 , 0.02107538, 0.83587967, 0.08655701, 0.92066482,
       0.17829419, 0.83957304, 0.12994345, 0.09475271, 0.97033969])

In [35]:
# randint

In [36]:
d = np.random.randint(10,50,40)
d

array([33, 18, 48, 11, 22, 11, 22, 25, 40, 16, 45, 25, 22, 46, 37, 49, 14,
       30, 22, 39, 36, 42, 10, 37, 16, 18, 28, 31, 42, 44, 29, 37, 32, 34,
       28, 34, 11, 40, 41, 32])

In [37]:
# Data Type

In [38]:
var = np.array([1,2,3,4,85,65,78,94,12])
print("Data Type : ",var.dtype)

Data Type :  int32


In [39]:
vr = np.array(["A","B","C","D"])
vr

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [40]:
v = np.array(["A","B","C","D",1,2,3,4])
v

array(['A', 'B', 'C', 'D', '1', '2', '3', '4'], dtype='<U11')

In [41]:
# Data Typecasting for Array

In [42]:
arr = np.array([1,2,3,45,68,94,2,5,6,78,2,58,91,3,45,18], dtype = np.int64)

print(arr)
arr.dtype

[ 1  2  3 45 68 94  2  5  6 78  2 58 91  3 45 18]


dtype('int64')

In [43]:
ar1 = np.array([1,2,3,45,68,94,2,5,6,78,2,58,91,3,45,18], dtype = "f")

print(ar1)
ar1.dtype

[ 1.  2.  3. 45. 68. 94.  2.  5.  6. 78.  2. 58. 91.  3. 45. 18.]


dtype('float32')

In [44]:
ar2 = np.array([1,2,3,4,5])
new = np.float32(ar2)
newb = np.bool_(ar2)
print(arr.dtype)
print(new.dtype)
print(newb)

int64
float32
[ True  True  True  True  True]


In [45]:
ar2.astype(float)

array([1., 2., 3., 4., 5.])

In [46]:
# Arithmatic Operations in Array

In [47]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

In [48]:
# Addition
add = np.add(a,b)
print(add)
print(a + 3)

[ 70  90 110 130 150]
[13 23 33 43 53]


In [49]:
#Substraction
sub = np.subtract(b,a)
print(sub)
print(a - 5)

[50 50 50 50 50]
[ 5 15 25 35 45]


In [50]:
# Multification
mul = np.multiply(a,b)
print(mul)
print(a * 5)

[ 600 1400 2400 3600 5000]
[ 50 100 150 200 250]


In [51]:
# Division 
div = np.divide(b,a)
print(div)
print(a/2)

[6.         3.5        2.66666667 2.25       2.        ]
[ 5. 10. 15. 20. 25.]


In [52]:
# Modules
mod = np.mod(b,a)
print(mod)
print(a%3)

[ 0 10 20 10  0]
[1 2 0 1 2]


In [53]:
# Power
power = np.power(b,a)
print(power)
print(a**2)

[-972029952 1896873984          0          0          0]
[ 100  400  900 1600 2500]


In [54]:
# Reciprocal
reci = np.reciprocal(a)
print(reci)
print(2/a)

[0 0 0 0 0]
[0.2        0.1        0.06666667 0.05       0.04      ]


In [55]:
# For Two-Dimension Arrays

In [56]:
var21 = np.array([[1,2,3,4,5],[11,12,13,14,15]])
var22 = np.array([[1,2,3,4,5],[11,12,13,14,15]])
newvar = np.add(var21,var22)
var21 = var21 + 3
print(var21)
print(newvar)

[[ 4  5  6  7  8]
 [14 15 16 17 18]]
[[ 2  4  6  8 10]
 [22 24 26 28 30]]


In [57]:
# Arithmatic operations 

In [58]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [59]:
# Minimum from the array
mini = np.min(a)
mini

10

In [60]:
# Maximum number from the Array
maxi = np.max(a)
maxi

50

In [61]:
# It is used for findout min/max position in array
b = np.array([55,45,62,32,78,65,63])

ag = np.argmin(b)

ax = np.argmax(b)

print(ag)
print(ax)

3
4


In [62]:
# Find out the sqrt of arrays element
asqrt = np.sqrt(a)
asqrt

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [63]:
# Sin value for Array elements
sin = np.sin(a)
sin

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [64]:
# cos values for Array elements
cos = np.cos(a)
cos

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [65]:
# cumsum of elements
cs = np.cumsum(a)
cs

array([ 10,  30,  60, 100, 150])

In [66]:
# shapes & Reshape of Arrays

var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [67]:
var1 = np.array([1,2,3,4,5],ndmin = 5)

var1

array([[[[[1, 2, 3, 4, 5]]]]])

In [68]:
# Reshape
rs = np.array([1,2,3,4,5,6,7,8,5,6,4,5,6,1,2,3])
x = rs.reshape(2,2,2,2)
x

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[5, 6],
         [4, 5]],

        [[6, 1],
         [2, 3]]]])

In [69]:
# Converting the One Dimension Array
one = x.reshape(-1)
one

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 4, 5, 6, 1, 2, 3])

In [70]:
# Boardcasting in numpy
p = np.array([1,2,3])
q = np.array([[1],[2],[3]])
print(p)
print(q)
r = p+q
print(r)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [71]:
x = np.array([1,2,3,4,5,6])
x = x.reshape(2,3)
y = np.array([1,2])
y = y.reshape(2,1)
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]


In [72]:
print(x + y)

[[2 3 4]
 [6 7 8]]


In [73]:
# Indexing

In [74]:
# 1D
var = np.array([1,2,3,4,5,6])
print(var[0])
print(var[-2])
print(var[3])

1
5
4


In [75]:
# 2D
var2 = np.array([[1,2,3,4],[5,6,7,8]])
print(var2[0,2])
print(var2[1][1])
print(var2[-1][-1])

3
6
8


In [76]:
# 3D
var3 = np.array([[[1,4,9],[7,5,3]],[[45,8,5],[7,85,6]]])
print(var3)
print(var3[1,0,0])
print(var3[1,1,0])
print(var3[0,1,1])

[[[ 1  4  9]
  [ 7  5  3]]

 [[45  8  5]
  [ 7 85  6]]]
45
7
5


In [77]:
# 1D Slicing

print(var[0:4])
print(var[1:-1])
print(var[-1:-5:-1])

[1 2 3 4]
[2 3 4 5]
[6 5 4 3]


In [78]:
# 2D Slicing

print(var2)
print(var2[1,1:2])
print(var2[0,2::2])
print(var2[1,4::-1])

[[1 2 3 4]
 [5 6 7 8]]
[6]
[3]
[8 7 6 5]


In [79]:
# 3D Slicing

print(var3)
print(var3[0,1,1:])
print(var3[1,1,1])
print(var3[1,0,0:1])

[[[ 1  4  9]
  [ 7  5  3]]

 [[45  8  5]
  [ 7 85  6]]]
[5 3]
85
[45]


In [80]:
# Iterating the Numpy
x = [9,7,8,4,6,5,3,1,2]
for i in x:
    print(i)

9
7
8
4
6
5
3
1
2


In [81]:
for x in var2:
    for m in x:
        print(m)

1
2
3
4
5
6
7
8


In [82]:
for i in np.nditer(var2):
    print(i)

1
2
3
4
5
6
7
8


In [83]:
for v in var3:
    for s in v:
        for w in s:
            print(w)


1
4
9
7
5
3
45
8
5
7
85
6


In [84]:
for i in np.nditer(var3,flags = ["buffered"],op_dtypes=["l"]):
    print(i)

1
4
9
7
5
3
45
8
5
7
85
6


In [85]:
# Copy and view

In [86]:
a = np.array([7,5,3,1,5,9])
c = np.copy(a)
c[0]=71
print(c)
print(a)

[71  5  3  1  5  9]
[7 5 3 1 5 9]


In [87]:
b = np.array([4,5,6,2,5,8])
v = b.view()
v[0]=40
print(b)
print(v)

[40  5  6  2  5  8]
[40  5  6  2  5  8]


In [88]:
d = np.array([1,4,7,8,9,6])
s = d
s[0] = 10
print(d)
print(s)

[10  4  7  8  9  6]
[10  4  7  8  9  6]


In [89]:
# Join Array

In [90]:
# 1D
qw = np.concatenate((a,x),axis = 0)
qw

array([7, 5, 3, 1, 5, 9, 5, 6, 7, 8])

In [91]:
b2 = np.array([[1,2,5,5],[8,6,2,5]])
print(b2)
print(var2)

[[1 2 5 5]
 [8 6 2 5]]
[[1 2 3 4]
 [5 6 7 8]]


In [92]:
w = np.concatenate((var2,b2),axis = 1)
w

array([[1, 2, 3, 4, 1, 2, 5, 5],
       [5, 6, 7, 8, 8, 6, 2, 5]])

In [93]:
print(var3)

[[[ 1  4  9]
  [ 7  5  3]]

 [[45  8  5]
  [ 7 85  6]]]


In [94]:
b3 = np.array([[[1,2,6],[4,5,8]],[[7,8,1],[8,9,7]]])
b3

array([[[1, 2, 6],
        [4, 5, 8]],

       [[7, 8, 1],
        [8, 9, 7]]])

In [95]:
we = np.concatenate((var3,b3),axis = 0)
we

array([[[ 1,  4,  9],
        [ 7,  5,  3]],

       [[45,  8,  5],
        [ 7, 85,  6]],

       [[ 1,  2,  6],
        [ 4,  5,  8]],

       [[ 7,  8,  1],
        [ 8,  9,  7]]])

In [96]:
fg= np.stack((var3,b3)) # Works as Vstack
fg

array([[[[ 1,  4,  9],
         [ 7,  5,  3]],

        [[45,  8,  5],
         [ 7, 85,  6]]],


       [[[ 1,  2,  6],
         [ 4,  5,  8]],

        [[ 7,  8,  1],
         [ 8,  9,  7]]]])

In [97]:
fgh= np.hstack((var3,b3)) # Works as Hstack
fgh

array([[[ 1,  4,  9],
        [ 7,  5,  3],
        [ 1,  2,  6],
        [ 4,  5,  8]],

       [[45,  8,  5],
        [ 7, 85,  6],
        [ 7,  8,  1],
        [ 8,  9,  7]]])

In [98]:
fgd= np.dstack((var3,b3)) # Works as Vstack
fgd

array([[[ 1,  4,  9,  1,  2,  6],
        [ 7,  5,  3,  4,  5,  8]],

       [[45,  8,  5,  7,  8,  1],
        [ 7, 85,  6,  8,  9,  7]]])

In [99]:
# Splitting Array

In [100]:
a

array([7, 5, 3, 1, 5, 9])

In [101]:
f = np.array_split(a,7)
f

[array([7]),
 array([5]),
 array([3]),
 array([1]),
 array([5]),
 array([9]),
 array([], dtype=int32)]

In [102]:
f2 = np.array_split(var2,3,axis = 1)
f2

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [103]:
f3 = np.array_split(var3,3,axis = 2)
f3

[array([[[ 1],
         [ 7]],
 
        [[45],
         [ 7]]]),
 array([[[ 4],
         [ 5]],
 
        [[ 8],
         [85]]]),
 array([[[9],
         [3]],
 
        [[5],
         [6]]])]

In [104]:
# Searching

In [105]:
var = np.array([1,2,5,3,1,2,4,25,5,7,2,8,6,25,4,2,8,1])

In [106]:
z = np.where(var == 1)
z

(array([ 0,  4, 17], dtype=int64),)

In [107]:
x = np.where(var%2 == 0)
x

(array([ 1,  5,  6, 10, 11, 12, 14, 15, 16], dtype=int64),)

In [108]:
y = np.where(var == 25)
y

(array([ 7, 13], dtype=int64),)

In [109]:
# Search Sort array

In [110]:
so = np.arange(1,10,2)
so

array([1, 3, 5, 7, 9])

In [111]:
x1 = np.searchsorted(so,[10,1,5])
x1

array([5, 0, 2], dtype=int64)

In [112]:
a

array([7, 5, 3, 1, 5, 9])

In [113]:
z = np.sort(a)
z

array([1, 3, 5, 5, 7, 9])

In [114]:
s = np.array(["a","s","d"])
x = np.sort(s)
x

array(['a', 'd', 's'], dtype='<U1')

In [115]:
np.sort(var2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
np.sort(var3)

array([[[ 1,  4,  9],
        [ 3,  5,  7]],

       [[ 5,  8, 45],
        [ 6,  7, 85]]])

In [117]:
# Filter

In [118]:
s

array(['a', 's', 'd'], dtype='<U1')

In [119]:
f = [True,False,True]
n = s[f]
n

array(['a', 'd'], dtype='<U1')

In [120]:
# Shuffle

In [121]:
suf = np.array([1,2,3,4,5])
np.random.shuffle(suf)

In [122]:
suf

array([2, 5, 3, 1, 4])

In [123]:
# Uniqe

In [124]:
var

array([ 1,  2,  5,  3,  1,  2,  4, 25,  5,  7,  2,  8,  6, 25,  4,  2,  8,
        1])

In [125]:
x = np.unique(var,return_index = True,return_counts=True)
x

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 25]),
 array([ 0,  1,  3,  6,  2, 12,  9, 11,  7], dtype=int64),
 array([3, 4, 1, 2, 2, 1, 1, 2, 2], dtype=int64))

In [126]:
# Resizing

In [127]:
rp = var.reshape(6,3,1)
print(rp)


[[[ 1]
  [ 2]
  [ 5]]

 [[ 3]
  [ 1]
  [ 2]]

 [[ 4]
  [25]
  [ 5]]

 [[ 7]
  [ 2]
  [ 8]]

 [[ 6]
  [25]
  [ 4]]

 [[ 2]
  [ 8]
  [ 1]]]


In [128]:
len(var)

18

In [129]:
rz = np.resize(var,(6,3,1))
print(rz)

[[[ 1]
  [ 2]
  [ 5]]

 [[ 3]
  [ 1]
  [ 2]]

 [[ 4]
  [25]
  [ 5]]

 [[ 7]
  [ 2]
  [ 8]]

 [[ 6]
  [25]
  [ 4]]

 [[ 2]
  [ 8]
  [ 1]]]


In [130]:
# Flatten

In [131]:
print(rz.flatten())

[ 1  2  5  3  1  2  4 25  5  7  2  8  6 25  4  2  8  1]


In [132]:
# Ravel

In [133]:
print(np.ravel(rz))

[ 1  2  5  3  1  2  4 25  5  7  2  8  6 25  4  2  8  1]


In [134]:
# Insertion, Update and delation

In [135]:
var

array([ 1,  2,  5,  3,  1,  2,  4, 25,  5,  7,  2,  8,  6, 25,  4,  2,  8,
        1])

In [136]:
np.insert(var,(0,3),100)

array([100,   1,   2,   5, 100,   3,   1,   2,   4,  25,   5,   7,   2,
         8,   6,  25,   4,   2,   8,   1])

In [137]:
var2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
np.insert(var2,(0,2),[100,14,1,5],axis = 0)

array([[100,  14,   1,   5],
       [  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [100,  14,   1,   5]])

In [139]:
var3

array([[[ 1,  4,  9],
        [ 7,  5,  3]],

       [[45,  8,  5],
        [ 7, 85,  6]]])

In [140]:
np.insert(var3,(2,2,1),[45,45,85],axis = 2)

array([[[ 1, 85,  4, 45, 45,  9],
        [ 7, 85,  5, 45, 45,  3]],

       [[45, 85,  8, 45, 45,  5],
        [ 7, 85, 85, 45, 45,  6]]])

In [141]:
# Append

In [142]:
x = np.append(var,6.5)

In [143]:
x

array([ 1. ,  2. ,  5. ,  3. ,  1. ,  2. ,  4. , 25. ,  5. ,  7. ,  2. ,
        8. ,  6. , 25. ,  4. ,  2. ,  8. ,  1. ,  6.5])

In [144]:
y = np.append(var2, [[1,2,3,4]], axis=0),
print(y),

(array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]]),)


(None,)

In [145]:
# z = np.append(var3,([[1],[2],[3]]),axis = 1)

In [146]:
# Delation

In [147]:
var

array([ 1,  2,  5,  3,  1,  2,  4, 25,  5,  7,  2,  8,  6, 25,  4,  2,  8,
        1])

In [148]:
d = np.delete(var,[3,5,6])
d

array([ 1,  2,  5,  1, 25,  5,  7,  2,  8,  6, 25,  4,  2,  8,  1])

In [149]:
d2 = np.delete(var2,[1,2],axis = 1)
d2

array([[1, 4],
       [5, 8]])

In [150]:
var2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])